version: '3'

services:
  app:
    build: .
    environment:
      - DELAY=60
      - DEBUG=True
      - PRODUCTION=True
      - BOT_TOKEN=
      - CLIENT_ID=
      - CLIENT_SECRET=
      - SANDBOX_ID=
      - SANDBOX_SECRET=
